## 1. Import the numpy package under the name np (★☆☆)

In [3]:
import numpy as np

## 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.19.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['openblas.dll', 'blas']
    library_dirs = ['/opt/sagemath-9.2/local/lib', '/usr/lib']
    include_dirs = ['/usr/include', '/opt/sagemath-9.2/local/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['openblas.dll', 'blas']
    library_dirs = ['/opt/sagemath-9.2/local/lib', '/usr/lib']
    include_dirs = ['/usr/include', '/opt/sagemath-9.2/local/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:

## 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4. How to find the memory size of any array (★☆☆)

In [5]:
Z = np.ones((2, 3))
print("%d bytes" % (Z.size * Z.itemsize))

48 bytes


## 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [1]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-1-1663cd30cb7c>, line 1)

## 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


## 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


## 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.57976872 0.98287375 0.13381296]
  [0.35911479 0.42685916 0.35450499]
  [0.72872536 0.6213645  0.99954722]]

 [[0.30911948 0.49106247 0.76897354]
  [0.22889407 0.93831373 0.22013041]
  [0.56441254 0.53187239 0.50382128]]

 [[0.77982746 0.70962144 0.12171896]
  [0.40093876 0.92204914 0.27565351]
  [0.86011086 0.11735628 0.91845864]]]


## 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0011108206875799498 0.9948300053912436


## 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5224394685364687


## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 17. What is the result of the following expression? (★☆☆)

In [25]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
Z = np.diag(1 + np.arange(4), k =-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [28]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [29]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


## 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [4]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22. Normalize a 5x5 random matrix (★☆☆)

In [5]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.60789006 -0.135385    1.56621401 -1.07985491 -0.87446722]
 [-1.51648594  1.58498513  1.01177959 -0.61375067  0.87108806]
 [-1.00191068  0.75700994  0.31814438  0.13472796  0.67618063]
 [ 0.41211873 -1.2524467   0.58929044  0.24762879 -1.1181678 ]
 [-1.70358055 -0.24025052  1.19323956 -0.9154165  -0.5185808 ]]


## 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [6]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [8]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [24]:
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [25]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 3]


In [26]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [29]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2023-03-30
2023-03-31
2023-04-01


In [30]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [31]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [32]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[2. 2. 1. 8. 6. 9. 0. 9. 8. 1.]
[2. 2. 1. 8. 6. 9. 0. 9. 8. 1.]
[2. 2. 1. 8. 6. 9. 0. 9. 8. 1.]
[2 2 1 8 6 9 0 9 8 1]
[2. 2. 1. 8. 6. 9. 0. 9. 8. 1.]


In [33]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [34]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [35]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [36]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.11374985 0.16598184 0.20505073 0.24345626 0.26316788 0.46914017
 0.57789652 0.70927651 0.78816627 0.95809263]


In [37]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [38]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


In [39]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [40]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.80779775 0.64161735 0.9169311  0.91864155 0.74124681 0.45358519
 1.1333072  1.08961147 0.93987147 0.31944052]
[1.21869205 0.54422361 1.19226459 1.25834797 1.49957399 1.51549539
 0.92266592 1.00758377 0.79392374 1.09396482]


In [41]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.73592385 0.47352627 0.246598   0.         0.15104359 0.6561018
 0.34550556 0.52755591 0.03356317 0.1846816 ]


In [42]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [43]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [44]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [45]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

24


In [47]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/opt/sagemath-9.2/local/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [49]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.71813053 0.93757428 0.39634019 0.66930892 0.27186392
  0.1081038  1.16041408 0.80123213 0.50164443]
 [0.71813053 0.         0.55527731 0.46776921 0.05035369 0.67579596
  0.62704511 0.68532576 0.16749401 0.51294292]
 [0.93757428 0.55527731 0.         0.90710638 0.57253781 0.72782861
  0.83014664 0.22897043 0.70749643 0.45008667]
 [0.39634019 0.46776921 0.90710638 0.         0.41989451 0.54289364
  0.36836145 1.09341379 0.47825021 0.59844252]
 [0.66930892 0.05035369 0.57253781 0.41989451 0.         0.63569102
  0.57955694 0.71553281 0.18341697 0.48811503]
 [0.27186392 0.67579596 0.72782861 0.54289364 0.63569102 0.
  0.20127497 0.95659221 0.80528064 0.27818273]
 [0.1081038  0.62704511 0.83014664 0.36836145 0.57955694 0.20127497
  0.         1.05248927 0.72338756 0.39845675]
 [1.16041408 0.68532576 0.22897043 1.09341379 0.71553281 0.95659221
  1.05248927 0.         0.81135184 0.67861787]
 [0.80123213 0.16749401 0.70749643 0.47825021 0.18341697 0.80528064
  0.72338756 0.81135

In [50]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[83 97 97 95 53 55 63 98 14 11]


In [51]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [52]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [53]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [54]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.30607907 -0.03059894  0.22255176  0.33400329  0.01830164 -0.36411637
   0.11201108  0.03721398 -0.32402584  0.30073846]
 [-0.31989298 -0.13250215 -0.30302245 -0.43435536  0.31154636  0.39041181
   0.11273033  0.20639135  0.1751155  -0.00642241]
 [-0.06909337 -0.41886448 -0.28160862 -0.44847609  0.1390022   0.11909968
   0.27665715  0.18085971  0.05834291  0.44408091]
 [-0.31947178 -0.2601776  -0.25427538 -0.23633138  0.54899771  0.5600988
  -0.12599056  0.30229487  0.06265693 -0.27780161]
 [-0.00353278 -0.50923338  0.23717073 -0.06040753 -0.07702563  0.27534845
  -0.45401109 -0.22111508  0.40281336  0.40999295]]


In [56]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 9 6]
 [0 1 8]
 [7 1 0]]
[[0 1 8]
 [7 1 0]
 [8 9 6]]


In [57]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [58]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5338126574018274


In [59]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [60]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [61]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[4. 4. 2. 4. 4. 1. 1. 3. 2. 5.]


In [62]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [63]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [64]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[67 45 62 40]
 [50 54 48 48]
 [52 52 69 51]]


In [65]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52364452 0.4681479  0.55991301 0.46891103 0.71475743 0.51690411
 0.42476963 0.5420063  0.45685798 0.6840864 ]


In [66]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.03949283, 1.25879337, 1.93888659, 0.93721128, 2.01395657])

In [67]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [68]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [69]:

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [70]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 42) ( 6, 83) ( 9, 34) ( 9, 83) (15, 71) (15, 98) (20, 72) (20, 85)
 (24, 32) (24, 37) (24, 64) (24, 65) (31, 58) (31, 71) (32, 65) (32, 75)
 (32, 88) (34, 83) (37, 64) (42, 83) (52, 61) (52, 90) (54, 92) (54, 95)
 (58, 71) (61, 90) (71, 98) (72, 85) (75, 88) (92, 95)]


In [71]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [72]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [73]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [74]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-2.66838757e-01,  6.79417118e-01, -4.75645489e-01, -2.91043316e-02,
        5.30942482e-01,  2.97261197e-01,  2.98172150e-01, -3.34181797e-01,
       -1.22479219e-01, -5.41832056e-01, -6.49677408e-01, -6.47951085e-01,
        4.94314768e-01, -2.63288415e-01, -4.25935489e-01, -3.47968110e-01,
        5.60766285e-01, -4.36845195e-01,  5.08574569e-01,  7.35748697e-03,
       -3.96029825e-02,  1.93364632e-01, -6.49156304e-01,  5.66628705e-01,
        9.36015581e-01, -2.18371399e-02,  8.24747021e-01,  7.93133934e-01,
       -8.35446803e-01, -9.88134986e-01,  7.07408961e-01,  2.95910526e-01,
        4.24117621e-01, -1.73486762e-01,  1.29473796e-01,  5.24850720e-01,
       -8.67180532e-01,  3.44111497e-01,  3.54502145e-01, -3.51205974e-01,
        6.85443557e-01,  3.48754594e-01, -2.67568241e-01,  4.13886494e-01,
       -4.06079656e-01, -7.08585164e-01,  8.97238344e-01, -5.24942260e-02,
       -7.36122853e-01,  5.06577681e-02, -6.15223959e-05,  9.06557072e-01,
        7.57854869e-01, -

In [75]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 8.47620354 12.86779982 10.33983606  0.97506405 11.63895743  9.90253795
  5.88251888 15.51695066  7.57498355  0.59513801]


In [76]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[4.51743144e+00 8.85973660e+00 7.91101947e+00 1.63386635e+01
  2.86272375e+00 2.00152581e+00 6.93025960e+00 1.20384021e+00
  4.75960069e-01 1.53439173e+01]
 [1.17849959e+01 3.50575055e+00 2.09750662e-02 9.17832739e+00
  7.24153408e+00 9.29632892e+00 1.58877021e+00 9.52427946e+00
  5.57013032e+00 1.14339347e+01]
 [4.22965430e+00 1.74340380e+00 4.48612910e+00 1.15918960e+01
  7.71837105e+00 6.71558672e+00 1.99430331e-01 6.04185102e+00
  9.83880888e+00 6.88442062e+00]
 [1.24450393e+01 6.70119883e+00 2.81257869e+00 1.21566479e+01
  9.08114900e+00 9.94180720e+00 4.78489634e+00 9.52824992e+00
  7.16864073e+00 1.46533352e+01]
 [1.13445390e+00 4.34866262e+00 2.50637281e+00 4.78546919e+00
  7.34636946e+00 3.59114436e+00 6.28570126e+00 1.71997201e+00
  8.84524769e+00 1.51832627e+00]
 [4.03005224e+00 1.48089283e+01 1.37668212e+01 2.23284073e+01
  4.75843728e+00 1.48644872e+00 1.28779192e+01 4.95490655e-01
  1.85897006e+00 2.10335137e+01]
 [1.73483101e+01 5.15428456e+00 5.42698063e-01 9.36125495e

In [77]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 2 9 5 4 7 5 8 3 8]
 [1 8 5 3 4 4 1 8 6 4]
 [2 5 4 7 0 9 0 3 8 2]
 [0 6 2 8 0 6 4 6 4 9]
 [5 0 9 3 9 9 9 7 8 1]
 [0 4 6 1 4 1 4 3 3 8]
 [7 2 1 4 6 2 5 1 2 8]
 [0 9 5 7 0 7 1 7 0 4]
 [9 7 7 9 8 7 2 0 4 5]
 [4 2 5 6 9 5 4 5 3 8]]
[[0 0 0 0 0]
 [0 8 2 9 5]
 [0 1 8 5 3]
 [0 2 5 4 7]
 [0 0 6 2 8]]


/opt/sagemath-9.2/local/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [78]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [79]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [80]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


In [81]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 0 1]
   [4 4 3]
   [1 2 3]]

  [[0 1 3]
   [4 3 1]
   [2 3 1]]

  [[1 3 1]
   [3 1 1]
   [3 1 1]]

  [[3 1 4]
   [1 1 2]
   [1 1 2]]

  [[1 4 2]
   [1 2 4]
   [1 2 2]]

  [[4 2 4]
   [2 4 0]
   [2 2 3]]

  [[2 4 4]
   [4 0 4]
   [2 3 0]]

  [[4 4 1]
   [0 4 1]
   [3 0 1]]]


 [[[4 4 3]
   [1 2 3]
   [0 2 0]]

  [[4 3 1]
   [2 3 1]
   [2 0 0]]

  [[3 1 1]
   [3 1 1]
   [0 0 1]]

  [[1 1 2]
   [1 1 2]
   [0 1 1]]

  [[1 2 4]
   [1 2 2]
   [1 1 4]]

  [[2 4 0]
   [2 2 3]
   [1 4 0]]

  [[4 0 4]
   [2 3 0]
   [4 0 1]]

  [[0 4 1]
   [3 0 1]
   [0 1 3]]]


 [[[1 2 3]
   [0 2 0]
   [2 4 2]]

  [[2 3 1]
   [2 0 0]
   [4 2 2]]

  [[3 1 1]
   [0 0 1]
   [2 2 4]]

  [[1 1 2]
   [0 1 1]
   [2 4 1]]

  [[1 2 2]
   [1 1 4]
   [4 1 0]]

  [[2 2 3]
   [1 4 0]
   [1 0 4]]

  [[2 3 0]
   [4 0 1]
   [0 4 0]]

  [[3 0 1]
   [0 1 3]
   [4 0 3]]]


 [[[0 2 0]
   [2 4 2]
   [3 3 0]]

  [[2 0 0]
   [4 2 2]
   [3 0 1]]

  [[0 0 1]
   [2 2 4]
   [0 1 1]]

  [[0 1 1]
   [2 4 1]
   [1 1 4]]

  [[1 1 4]
   

In [82]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  9 17 10  9]
 [ 9  0  8 10  2]
 [17  8  9 42 11]
 [10 10 42  0 17]
 [ 9  2 11 17  9]]


In [83]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [84]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [85]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 1 1 1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
89. How to get the n largest values of an array (★★★)

In [86]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


In [87]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [88]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [92]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

KeyboardInterrupt: 

In [93]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 4 5 6 7]


In [94]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)


[[2 4 4]
 [2 3 4]
 [4 4 3]
 [2 2 0]
 [1 1 0]
 [1 4 3]
 [3 2 0]
 [2 1 4]
 [2 2 0]
 [3 4 3]]
[[2 4 4]
 [2 3 4]
 [4 4 3]
 [2 2 0]
 [1 1 0]
 [1 4 3]
 [3 2 0]
 [2 1 4]
 [2 2 0]
 [3 4 3]]


In [95]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [96]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


In [97]:

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.02887719, 0.0257341 , 0.02556297, 0.03508642, 0.04016196,
        0.0273268 , 0.02604166, 0.03381549, 0.03488408, 0.03484887],
       [0.32966481, 0.29378299, 0.29182934, 0.40055004, 0.45849285,
        0.31196542, 0.29729411, 0.38604089, 0.39824004, 0.39783814],
       [0.27794642, 0.2476938 , 0.24604664, 0.33771105, 0.38656369,
        0.26302374, 0.25065409, 0.32547812, 0.33576345, 0.3354246 ],
       [0.31976361, 0.28495947, 0.28306449, 0.38851986, 0.44472241,
        0.3025958 , 0.28836513, 0.37444648, 0.38627924, 0.38588941],
       [0.34647805, 0.30876622, 0.30671293, 0.42097849, 0.48187645,
        0.32787596, 0.31245641, 0.40572936, 0.41855068, 0.41812828],
       [0.07836938, 0.0698394 , 0.06937497, 0.09522053, 0.10899496,
        0.0741618 , 0.07067408, 0.09177135, 0.09467139, 0.09457585],
       [0.26563698, 0.23672416, 0.23514995, 0.3227548 , 0.36944391,
        0.25137518, 0.23955335, 0.31106364, 0.32089346, 0.32056962],
       [0.07192332, 0.06409494, 0.0636687

In [98]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

In [99]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12667853  0.26384514]
